apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                  configMapKeyRef:
                    name: postgres-config
                    key: postgres_user
            - name: POSTGRES_DB
              valueFrom:
                  configMapKeyRef:
                    name: postgres-config
                    key: postgres_db
            - name: PGDATA # Explicitly define PGDATA to match mountPath
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data # Changed mountPath
          resources:
            limits:
              cpu: "0.50"
              memory: "128Mi"
            requests:
              cpu: "0.25"
              memory: "64Mi"
  volumeClaimTemplates: # Added this section for StatefulSet storage management
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi