apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  description: Pipeline with custom git-clone step
  params:
    - name: GIT_REPO
      type: string
      description: The Git repository to clone
    - name: GIT_REF
      type: string
      default: "main"
      description: The Git branch, tag, or commit to check out
    - name: APP_NAME
      type: string
      default: "petshop"
      description: Name of the application
    - name: IMAGE_NAME
      type: string
      default: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.APP_NAME):latest'
      description: Name of the image to build
  workspaces:
    - name: pipeline-workspace
      description: Shared workspace for all pipeline tasks
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: repo-url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REF)
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: BUILD_ARGS
          value: []
        - name: CONTEXT
          value: .
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
        - name: TLS_VERIFY
          value: 'true'
        - name: VERBOSE
          value: 'false'
      runAfter:
        - pylint
        - testing
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah-1-19-0
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: pipeline-workspace
