apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: github-webhook-route
spec:
  to:
    kind: Service
    name: el-cd-listener
  port:
    targetPort: http-listener
  tls:
    termination: edge
